[project]
name = "zotmcp"
version = "0.1.0"
description = "MCP server for semantic search of Zotero academic library"
authors = [{name = "Nicolas Suzor", email = "nic@suzor.com"}]
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.2.0",
    "chromadb>=0.4.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "jupyter>=1.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
