# @package _global_
# Zotero Vectorization Pipeline for ZotMCP
#
# Usage: python -m buttermilk.pipeline.runner --config-path conf --config-name vectorize

defaults:
  - zotero
  - _self_

run:
  mode: pipeline

bm:
  _target_: buttermilk._core.bm_init.BM
  session_info:
    project_name: zotmcp
    job: vectorize_zotero
    template_paths:
      - templates

storage:
  zotero_vectors:
    # Just change the persist_directory to point to the upstream authoritative version
    # So that any changes we make will be synchronised.
    persist_directory: "gs://prosocial-dev/data/zotero-prosocial-fulltext/files"

vectoriser:
  _target_: buttermilk.data.vector.ChromaDBEmbeddings
  persist_directory: ${storage.zotero_vectors.persist_directory}
  collection_name: ${storage.zotero_vectors.collection_name}
  embedding_model: ${storage.zotero_vectors.embedding_model}
  dimensionality: ${storage.zotero_vectors.dimensionality}
  concurrency: ${pipeline.concurrency}
  sync_batch_size: 500
  deduplication_strategy: record_id  # Skip existing records before downloading
  enable_record_cache: true

pipeline:
  _target_: buttermilk.pipeline.PipelineOrchestrator
  pipeline_name: zotero_vectorization
  concurrency: 1
  max_records: 999999

  # Source: Zotero library with deduplication filter
  source:
    _target_: buttermilk.libs.zotero.ZoteroSource
    library_id: ${oc.env:ZOTERO_LIBRARY_ID}
    save_dir: ${oc.env:HOME}/.cache/buttermilk/zotero/state
    filter:
      _target_: buttermilk.libs.zotero.VectorStoreExistenceFilter
      vector_store: ${vectoriser}
    force_full_sync: true
    start: 0
    max_records: ${pipeline.max_records}

  processors:
    # 0. Download PDFs and extract full text
    - _target_: buttermilk.libs.zotero.ZoteroDownloadProcessor
      library_id: ${oc.env:ZOTERO_LIBRARY_ID}
      save_dir: ${oc.env:HOME}/.cache/buttermilk/zotero/items

    # 1. Generate citations using LLM
    - _target_: buttermilk.tools.citator.Citator
      model: gemini25flash
      template: citator

    # 2. Chunk text semantically
    - _target_: buttermilk.data.vector.SemanticSplitter
      chunk_size: 500
      chunk_overlap: 200

    # 3. Generate embeddings (pure, no side effects)
    - _target_: buttermilk.processors.embeddings.EmbeddingGenerator
      embedding_model: ${storage.zotero_vectors.embedding_model}
      dimensionality: ${storage.zotero_vectors.dimensionality}
      embedding_batch_size: 100
      embedding_max_retries: 5
      embedding_cooldown_seconds: 0.1

    # 4. Store in ChromaDB
    - ${vectoriser}

