# ZotMCP Configuration
# Used by the MCP server to access the Zotero library vector database

project_name: zotmcp
job: mcp_server
verbose: true

run:
  mode: mcp_server

session:
  project_name: ${project_name}
  job: ${job}

infrastructure:
  clouds:
    - type: gcp
      _target_: buttermilk._core.cloud_config.GCPConfig
      project_id: prosocial-443205
      region: us-central1
      location: us-central1
      storage_bucket: prosocial-dev
      secrets:
        _target_: buttermilk._core.cloud_config.SecretsServiceConfig
        models_secret: dev__llm__connections
        credentials_secret: dev__shared_credentials
      logging:
        _target_: buttermilk._core.cloud_config.LoggingServiceConfig
        enabled: true
        verbose: false
      pubsub:
        _target_: buttermilk._core.cloud_config.PubSubServiceConfig
        jobs_topic: jobs
        jobs_subscription: jobs-sub
        status_topic: flow
        status_subscription: flow-sub
      vertex:
        enabled: true

  tracing:
    weave:
      enabled: false
    otel:
      enabled: false

  logging:
    type: local
    verbose: true

storage:
  # Vector database for Zotero library
  # In the pipeline config, we reference the upstream version and update that.
  zotero_vectors:
    type: chromadb
    collection_name: prosocial_zot
    read_only: true

    # This is the path in that Docker image where we sync the GCS bucket
    persist_directory: /chromadb  
    
    embedding_model: gemini-embedding-001
    dimensionality: 3072


# Metadata fields to extract from Zotero items
zotero_fields:
  bibliographic:
    - title
    - creators
    - date
    - publicationTitle
    - publisher
    - DOI
    - url
    - itemType
    - abstractNote
    - pages
    - volume
    - issue

  technical:
    - item_key
    - document_id
    - chunk_index
    - embedding_model
