# ZotMCP Configuration
# Used by the MCP server to access the Zotero library vector database

run:
  mode: mcp_server

bm:
  _target_: buttermilk._core.bm_init.BM
  session_info:
    project_name: zotmcp
    job: mcp_server
    cache_dir: ".cache"

infrastructure:
  clouds:
    - type: gcp
      _target_: buttermilk._core.cloud_config.GCPConfig
      project_id: prosocial-443205
      region: us-central1
      location: us-central1
      storage_bucket: prosocial-dev
      secrets:
        _target_: buttermilk._core.cloud_config.SecretsServiceConfig
        models_secret: dev__llm__connections
        credentials_secret: dev__shared_credentials
      logging:
        _target_: buttermilk._core.cloud_config.LoggingServiceConfig
        verbose: false
      pubsub:
        _target_: buttermilk._core.cloud_config.PubSubServiceConfig
        jobs_topic: jobs
        jobs_subscription: jobs-sub
        status_topic: flow
        status_subscription: flow-sub
      vertex:
        enabled: true

  tracing:
    weave:
      enabled: false
    otel:
      enabled: false

  logging:
    type: local
    verbose: true

storage:
  # Vector database for Zotero library
  # This one only references the local cache.
  # In the pipeline config, we reference the upstream version and update that.
  zotero_vectors:
    type: chromadb
    collection_name: prosocial_zot
    persist_directory: /home/nic/src/writing/projects/zotmcp/.cache/zotero-prosocial-fulltext/files
    embedding_model: gemini-embedding-001
    dimensionality: 3072


# Metadata fields to extract from Zotero items
zotero_fields:
  bibliographic:
    - title
    - creators
    - date
    - publicationTitle
    - publisher
    - DOI
    - url
    - itemType
    - abstractNote
    - pages
    - volume
    - issue

  technical:
    - item_key
    - document_id
    - chunk_index
    - embedding_model
