# Minimal runtime configuration for ZotMCP
# Only enables Vertex AI embeddings for query vector conversion
# No cloud logging, secrets, pub/sub, or other infrastructure

bm:
  _target_: buttermilk._core.bm_init.BM
  session_info:
    project_name: zotmcp
    job: runtime
    cache_dir: ".cache"

infrastructure:
  clouds:
    - type: gcp
      _target_: buttermilk._core.cloud_config.GCPConfig
      project_id: prosocial-443205
      region: us-central1
      location: us-central1
      vertex:
        enabled: true  # Only for embeddings
      secrets: null     # No secrets
      logging: null     # No cloud logging
      pubsub: null      # No pub/sub

  tracing:
    weave:
      enabled: false
    otel:
      enabled: false

  logging:
    type: local
    verbose: true

storage:
  zotero_vectors:
    type: chromadb
    collection_name: prosocial_zot
    persist_directory: .cache/zotero-prosocial-fulltext/files
    embedding_model: gemini-embedding-001
    dimensionality: 3072
